version: "3.7"
services:

  adela.postgres:
    image: postgres:14
    container_name: adela.postgres
    restart: always
    volumes:
      - adela.postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  adela.mysql:
    image: mysql:8
    container_name: adela.mysql
    restart: always
    volumes:
      - adela.mysql:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env

  adela.mongo:
    image: mongo:6
    container_name: adela.mongo
    restart: always
    volumes:
      - adela.mongo:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env

volumes:
  adela.postgres:
  adela.mysql:
  adela.mongo: